spring:
  datasource:
    url: jdbc:mysql://dodoesdid.crwk4k4emcw3.ap-northeast-2.rds.amazonaws.com:3306/dodoesdid
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  data:
    redis:
      host: 3.35.176.89
      port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql: trace